### ISSUE TITLE
outdated dependency @types/cookie causes type mismatch

### ISSUE THREAD

**Issue by brumm** [vvo/iron-session#690]
Hey there,

I'm seeing a TS error when passing Nextjs's `cookies()` function to `getIronSession`

```
Argument of type 'ReadonlyRequestCookies' is not assignable to parameter of type 'CookieStore'.
  Types of property 'set' are incompatible.
    Type '(...args: [key: string, value: string, cookie?: Partial<ResponseCookie> | undefined] | [options: ResponseCookie]) => ResponseCookies' is not assignable to type '{ (name: string, value: string, cookie?: Partial<ResponseCookie> | undefined): void; (options: ResponseCookie): void; }'.
      Types of parameters 'args' and 'name' are incompatible.
        Type '[name: string, value: string, cookie?: Partial<ResponseCookie> | undefined]' is not assignable to type '[key: string, value: string, cookie?: Partial<ResponseCookie> | undefined] | [options: ResponseCookie]'.
          Type '[name: string, value: string, cookie?: Partial<ResponseCookie> | undefined]' is not assignable to type '[key: string, value: string, cookie?: Partial<ResponseCookie> | undefined]'.
            Type at position 2 in source is not compatible with type at position 2 in target.
              Type 'Partial<ResponseCookie> | undefined' is not assignable to type 'Partial<import("/Users/brumm/Code/portals/node_modules/next/dist/compiled/@edge-runtime/cookies/index").ResponseCookie> | undefined'.
                Type 'Partial<ResponseCookie>' is not assignable to type 'Partial<import("/Users/brumm/Code/portals/node_modules/next/dist/compiled/@edge-runtime/cookies/index").ResponseCookie>'.
                  Types of property 'priority' are incompatible.
                    Type 'unknown' is not assignable to type '"low" | "medium" | "high" | undefined'.ts(2345)
```

It seems like the `priority` attribute has been added to the types in `@types/cookie@0.6.0`, but this library is still on `0.5.4`

**Comment by aryaadinulfadlan** [comment]
> Hey there,
> 
> I'm seeing a TS error when passing Nextjs's `cookies()` function to `getIronSession`
> 
> ```
> Argument of type 'ReadonlyRequestCookies' is not assignable to parameter of type 'CookieStore'.
>   Types of property 'set' are incompatible.
>     Type '(...args: [key: string, value: string, cookie?: Partial<ResponseCookie> | undefined] | [options: ResponseCookie]) => ResponseCookies' is not assignable to type '{ (name: string, value: string, cookie?: Partial<ResponseCookie> | undefined): void; (options: ResponseCookie): void; }'.
>       Types of parameters 'args' and 'name' are incompatible.
>         Type '[name: string, value: string, cookie?: Partial<ResponseCookie> | undefined]' is not assignable to type '[key: string, value: string, cookie?: Partial<ResponseCookie> | undefined] | [options: ResponseCookie]'.
>           Type '[name: string, value: string, cookie?: Partial<ResponseCookie> | undefined]' is not assignable to type '[key: string, value: string, cookie?: Partial<ResponseCookie> | undefined]'.
>             Type at position 2 in source is not compatible with type at position 2 in target.
>               Type 'Partial<ResponseCookie> | undefined' is not assignable to type 'Partial<import("/Users/brumm/Code/portals/node_modules/next/dist/compiled/@edge-runtime/cookies/index").ResponseCookie> | undefined'.
>                 Type 'Partial<ResponseCookie>' is not assignable to type 'Partial<import("/Users/brumm/Code/portals/node_modules/next/dist/compiled/@edge-runtime/cookies/index").ResponseCookie>'.
>                   Types of property 'priority' are incompatible.
>                     Type 'unknown' is not assignable to type '"low" | "medium" | "high" | undefined'.ts(2345)
> ```
> 
> It seems like the `priority` attribute has been added to the types in `@types/cookie@0.6.0`, but this library is still on `0.5.4`

hello sir. I got the same error.
how to solve that?

**Comment by murieldelvaux** [comment]
Hello, I got the same error. How do we solve that?

**Comment by mordechaim** [comment]
I couldn't find a better way other than just use type assertion, ugly I know:

```ts
await getIronSession<SessionData>(cookies() as any, config)
```

**Comment by murieldelvaux** [comment]
I tried something similar, it worked, thank you very much!

**Comment by vvo** [comment]
Hey there, I upgraded cookies to 0.6.0 this should be solved? Let me know!

**Comment by vvo** [comment]
8.0.2 was released

**Comment by murieldelvaux** [comment]
Hello, I just updated to test, but I still get the same thing: "Argument of Type" Readonlyrequestcookies 'is not asquisignable to parameter of type' cookiestore'.ts (2345)
⚠ Error (TS2345) |
ARGUENT OF TYPE
 is not assignable to parameter of type
 . "

To solve this, I had to keep it as in the image below:
![image](https://github.com/vvo/iron-session/assets/87376098/dfcc7da0-d5e0-4e66-a839-d7f1a6eb2097)

**Comment by vvo** [comment]
@murieldelvaux Is there any chance you can create a simple github repository showing the issue? I do not get the problem currently.

**Comment by robknight** [comment]
I was able to resolve this by directly depending on `@types/cookie` in my project.
